modLoader="javafml"
loaderVersion="[4,)"
license="Creative Commons Attribution 4.0 International Public License"

[[mods]]
modId="antlers_of_the_winter"
version="1.0.0"
displayName="Antlers of the Winter"
displayURL="https://bit.ly/antlers-of-the-winter"
authors="Vuserr"
description="Step into a frozen dimension filled with unique biomes, mobs, and resources. Craft powerful horns and frozen gear to survive the harsh cold. Explore the icy wastelands and uncover the secrets hidden within this chilling new world."
displayTest="IGNORE_SERVER_VERSION"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.antlers_of_the_winter]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.65,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.antlers_of_the_winter]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration